# -*- coding: utf-8 -*-
"""Gráficos gráfica

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19yZ8zH8aMq5brPmYSxE2ShwfxrbPmhcB
"""

import altair as alt
import pandas as pd

# Tus datos
data = pd.DataFrame({
    'categoria': ['Mujeres', 'Hombres', 'Mixto'],
    'cantidad': [159, 626, 67]
})

# Colores en el mismo orden de las categorías
colores = ['#7E4782',  # Mujeres (lila)
           '#2E3566',  # Hombres (azul medio)
           '#8FA3CC']  # Mixto (celeste lila)

# Gráfico
chart = alt.Chart(data).mark_bar().encode(
    x=alt.X('categoria:N', title='Categoría'),
    y=alt.Y('cantidad:Q', title='Cantidad'),
    color=alt.Color('categoria:N',
                    scale=alt.Scale(range=colores),
                    title='Categoría')
).properties(
    width=400,
    height=300,
    title='Distribución por categoría'
)

chart

import altair as alt
import pandas as pd

# Datos entregados
data = pd.DataFrame({
    'Año': [2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,
            2012,2013,2014,2015,2016,2017,2018,2019,2020,
            2023,2024,2025],
    'Hombre': [16,17,23,17,15,13,12,14,8,11,15,13,13,14,11,9,11,10,8,5,9,10],
    'Mixto':  [4,2,0,2,3,2,3,1,1,2,0,1,1,0,0,1,1,0,1,1,1,1],
    'Mujer':  [8,1,2,3,0,1,1,0,1,1,1,2,3,1,1,4,1,3,4,6,2,2]
})

# Reestructurar a formato largo
data_long = data.melt(id_vars='Año',
                      value_vars=['Hombre', 'Mixto', 'Mujer'],
                      var_name='Categoria',
                      value_name='Cantidad')

# Colores asignados
colores = {
    'Hombre': '#7E4782',   # azul medio
    'Mujer': '#2E3566',    # lila
    'Mixto': '#8FA3CC'     # celeste lila
}

# Gráfico de líneas o área (elige uno descomentando)

# --- Gráfico de área ---
chart = alt.Chart(data_long).mark_area().encode(
    x=alt.X('Año:O', title='Año'),
    y=alt.Y('Cantidad:Q', title='Cantidad'),
    color=alt.Color('Categoria:N',
                    scale=alt.Scale(domain=list(colores.keys()),
                                    range=list(colores.values())),
                    title='Categoría')
).properties(
    width=600,
    height=350,
    title='Distribución por Categoría (2002–2025)'
)

chart

import altair as alt
import pandas as pd

# Datos entregados (limpiados, sin vacíos)
data = pd.DataFrame({
    'Año': [2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,
            2012,2013,2014,2015,2016,2017,2018,2019,2020,
            2023,2024,2025],
    'Hombre': [16,17,23,17,15,13,12,14,8,11,15,13,13,14,11,9,11,10,8,5,9,10],
    'Mixto':  [4,2,0,2, 3,2,3,1,1,2,0,1,1,0,0,1,1,0,1,1,1,1],
    'Mujer':  [8,1,2,3,0,1,1,0,1,1,1,2,3,1,1,4,1,3,4,6,2,2]
})

# Reestructurar a formato largo
data_long = data.melt(
    id_vars='Año',
    value_vars=['Hombre', 'Mujer', 'Mixto'],
    var_name='Categoria',
    value_name='Cantidad'
)

# Colores corregidos según lo que pediste
colores = {
    'Hombre': '#8FA3CC',   # celeste lila
    'Mujer': '#7E4782',    # lila
    'Mixto': '#2E3566'     # azul medio
}

# Gráfico de área
chart = alt.Chart(data_long).mark_area().encode(
    x=alt.X('Año:O', title='Año'),
    y=alt.Y('Cantidad:Q', title='Cantidad'),
    color=alt.Color(
        'Categoria:N',
        scale=alt.Scale(
            domain=list(colores.keys()),
            range=list(colores.values())
        ),
        title='Categoría'
    )
).properties(
    width=600,
    height=350,
    title='Distribución por Categoría (2002–2025)'
)

chart

import altair as alt
import pandas as pd

data = pd.DataFrame({
    'Año': [2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,
            2012,2013,2014,2015,2016,2017,2018,2019,2020,
            2023,2024,2025],
    'Hombre': [16,17,23,17,15,13,12,14,8,11,15,13,13,14,11,9,11,10,8,5,9,10],
    'Mixto':  [4,2,0,2,3,2,3,1,1,2,0,1,1,0,0,1,1,0,1,1,1,1],
    'Mujer':  [8,1,2,3,0,1,1,0,1,1,1,2,3,1,1,4,1,3,4,6,2,2]
})

data_long = data.melt(
    id_vars='Año',
    value_vars=['Hombre', 'Mujer', 'Mixto'],
    var_name='Categoria',
    value_name='Cantidad'
)

colores = {
    'Hombre': '#8FA3CC',
    'Mujer': '#7E4782',
    'Mixto': '#2E3566'
}

chart = alt.Chart(data_long).mark_area().encode(
    x=alt.X('Año:O'),
    y=alt.Y('Cantidad:Q'),
    color=alt.Color(
        'Categoria:N',
        scale=alt.Scale(domain=list(colores.keys()),
                        range=list(colores.values()))
    ),
).properties(
    width=600,
    height=350
).encode(
    y=alt.Y('Cantidad:Q', stack=None)   # 🔥 ESTA LÍNEA DESACTIVA EL STACKING
)

chart

import altair as alt
import pandas as pd

# Datos entregados
data = pd.DataFrame({
    'Año': [2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,
            2012,2013,2014,2015,2016,2017,2018,2019,2020,
            2023,2024,2025],
    'Hombre': [16,17,23,17,15,13,12,14,8,11,15,13,13,14,11,9,11,10,8,5,9,10],
    'Mixto':  [4,2,0,2,3,2,3,1,1,2,0,1,1,0,0,1,1,0,1,1,1,1],
    'Mujer':  [8,1,2,3,0,1,1,0,1,1,1,2,3,1,1,4,1,3,4,6,2,2]
})

# Pasar a formato largo como stocks()
data_long = data.melt(
    id_vars='Año',
    value_vars=['Hombre', 'Mujer', 'Mixto'],
    var_name='Categoria',
    value_name='Cantidad'
)

# Colores corregidos
colores = {
    'Hombre': '#8FA3CC',   # celeste lila
    'Mujer': '#7E4782',    # lila
    'Mixto': '#2E3566'     # azul medio
}

# Base
base = alt.Chart(data_long).encode(
    alt.Color("Categoria:N", scale=alt.Scale(domain=list(colores.keys()),
                                             range=list(colores.values())))
).properties(
    width=600
)

# Línea
line = base.mark_line().encode(
    x=alt.X("Año:O", title="Año"),
    y=alt.Y("Cantidad:Q", title="Cantidad")
)

# Último punto de cada categoría
last_point = base.mark_circle(size=60).encode(
    alt.X("Año:O"),
    alt.Y("Cantidad:Q")
).transform_aggregate(
    last_date="argmax(Año)",
    groupby=["Categoria"]
).transform_lookup(
    lookup="last_date",
    from_=alt.LookupData(data_long, "Año", ["Año", "Categoria", "Cantidad"])
)

# Nombre al lado del último punto
labels = last_point.mark_text(dx=5, dy=-5).encode(
    text="Categoria:N"
)

chart = line + last_point + labels
chart

import altair as alt
import pandas as pd

# Datos entregados
data = pd.DataFrame({
    'Año': [2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,
            2012,2013,2014,2015,2016,2017,2018,2019,2020,
            2023,2024,2025],
    'Hombre': [16,17,23,17,15,13,12,14,8,11,15,13,13,14,11,9,11,10,8,5,9,10],
    'Mixto':  [4,2,0,2,3,2,3,1,1,2,0,1,1,0,0,1,1,0,1,1,1,1],
    'Mujer':  [8,1,2,3,0,1,1,0,1,1,1,2,3,1,1,4,1,3,4,6,2,2]
})

# Largo
data_long = data.melt(
    id_vars='Año',
    value_vars=['Hombre', 'Mujer', 'Mixto'],
    var_name='Categoria',
    value_name='Cantidad'
)

# Colores
colores = {
    'Hombre': '#2E3566',
    'Mujer': '#7E4782',
    'Mixto': '#8FA3CC'
}

# Base
base = alt.Chart(data_long).encode(
    alt.Color("Categoria:N",
              scale=alt.Scale(domain=list(colores.keys()),
                              range=list(colores.values())))
).properties(width=600)

# Línea GRUESA
line = base.mark_line(strokeWidth=3).encode(
    x=alt.X("Año:O", title="Año"),
    y=alt.Y("Cantidad:Q", title="Cantidad")
)

# Último punto
last_point = base.mark_circle(size=70).encode(
    alt.X("Año:O"),
    alt.Y("Cantidad:Q")
).transform_aggregate(
    last_date="argmax(Año)",
    groupby=["Categoria"]
).transform_lookup(
    lookup="last_date",
    from_=alt.LookupData(data_long, "Año", ["Año", "Categoria", "Cantidad"])
)

# Etiquetas
labels = last_point.mark_text(dx=5, dy=-5).encode(
    text="Categoria:N"
)

chart = line + last_point + labels
chart