# -*- coding: utf-8 -*-
"""gráficos grafica Paloma

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EgOYPzxYhSu3SY-DToWe0hvTus2Ar6sZ
"""

import altair as alt
import pandas as pd

data = {
    "año": [2025, 2024, 2023, 2020, 2019, 2018, 2017, 2016,
            2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008,
            2007, 2006, 2005, 2004, 2003, 2002],
    "gaviota": [27, 24, 24, 24, 24, 26, 29, 24, 30, 34, 29, 20, 14, 9, 12, 12, 9, 8, 9, 23, 4, 4],
    "antorcha": [None, None, None, None, None, None, None, None,
                 None, 34, 32, 32, 28, 20, 15, 32, 32, 36, 44, 38, 23, 15]
}

df = pd.DataFrame(data)

df_melted = df.melt('año', var_name='variable', value_name='valor')

chart = alt.Chart(df_melted).mark_area(opacity=0.7).encode(
    x=alt.X('año:O', title='Año'),
    y=alt.Y('valor:Q', title='Cantidad'),
    color=alt.Color('variable:N', title='Categoría',
                    scale=alt.Scale(scheme='category10'))
).properties(
    title='Evolución de Gaviotas y Antorchas',
    width=600,
    height=350
)
chart

import altair as alt
import pandas as pd

# Datos
data = {
    "año": [2025, 2024, 2023, 2020, 2019, 2018, 2017, 2016,
            2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008,
            2007, 2006, 2005, 2004, 2003, 2002],
    "gaviota": [27, 24, 24, 24, 24, 26, 29, 24, 30, 34, 29, 20, 14, 9, 12, 12, 9, 8, 9, 23, 4, 4],
    "antorcha": [None, None, None, None, None, None, None, None,
                 None, 34, 32, 32, 28, 20, 15, 32, 32, 36, 44, 38, 23, 15]
}

df = pd.DataFrame(data)

# Transformar a formato largo
df_melted = df.melt('año', var_name='variable', value_name='valor')

# Colores personalizados
colores = ['#7E4782', '#8FA3CC']

# Gráfico tipo área
chart = alt.Chart(df_melted).mark_area(opacity=0.8).encode(
    x=alt.X('año:O', title='Año'),
    y=alt.Y('valor:Q', title='Cantidad'),
    color=alt.Color('variable:N',
                    title='Categoría',
                    scale=alt.Scale(domain=['gaviota', 'antorcha'],
                                    range=colores))
).properties(
    title='Evolución de Gaviotas y Antorchas',
    width=650,
    height=400
)

chart
# 2. Guardarlo como HTML
chart.save('mi_grafico.html')

# 3. Descargar el archivo
from google.colab import files
files.download('mi_grafico.html')